### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by AManWithPlan** [tooxo/Geiler-Musik-Bot#35]
I wanted to host the bot for myself, but couldn't get it running. I suppose recent updates made it require more than entering tokens.

**Comment by tooxo** [comment]
How did you try to start the bot? I don't think the readme is out of date.

**Comment by AManWithPlan** [comment]
With src/discord_main.py. Yeah might have been my error.

**Comment by tooxo** [comment]
The recommended way is starting it via docker-compose.

**Comment by AManWithPlan** [comment]
Great, thanks
